package dev.alejandrosahonero.app;

import dev.alejandrosahonero.db.Alumno;
import dev.alejandrosahonero.db.Conector;
import dev.alejandrosahonero.db.Profesor;
import dev.alejandrosahonero.gui.welcome.StartView;

import javax.persistence.EntityManager;
import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        StartView startView = new StartView();
        startView.setVisible(true);

        //Alumnos de ejemplo para tener una base de datos
        EntityManager em = Conector.getEntityManager();
        em.getTransaction().begin();
        Alumno a1 = new Alumno("12345678A", "García", "López", "Ana", 19, "Femenino", 1001, new ArrayList<>(List.of("Programación", "Bases de Datos")));
        Alumno a2 = new Alumno("87654321B", "Pérez", "Ramírez", "Carlos", 20, "Masculino", 1002, new ArrayList<>(List.of("Entornos de Desarrollo", "Sistemas Informáticos")));
        Alumno a3 = new Alumno("45678912C", "López", "Martínez", "María", 18, "Femenino", 1003, new ArrayList<>(List.of("Lenguajes de Marcas", "FOL")));
        Alumno a4 = new Alumno("78945612D", "Sánchez", "Castillo", "Luis", 21, "Masculino", 1004, new ArrayList<>(List.of("Programación", "Sistemas Informáticos")));
        Alumno a5 = new Alumno("32165487E", "Martínez", "Gómez", "Lucía", 22, "Femenino", 1005, new ArrayList<>(List.of("Bases de Datos", "FOL")));
        Alumno a6 = new Alumno("14785236F", "Fernández", "Navarro", "Javier", 19, "Masculino", 1006, new ArrayList<>(List.of("Lenguajes de Marcas", "Entornos de Desarrollo")));
        Alumno a7 = new Alumno("96325874G", "Torres", "Moreno", "Elena", 20, "Femenino", 1007, new ArrayList<>(List.of("Programación", "FOL")));
        Alumno a8 = new Alumno("85274196H", "Ramírez", "Silva", "Sergio", 23, "Masculino", 1008, new ArrayList<>(List.of("Bases de Datos", "Entornos de Desarrollo")));
        Alumno a9 = new Alumno("15975348I", "Morales", "Cruz", "Andrea", 18, "Femenino", 1009, new ArrayList<>(List.of("Sistemas Informáticos", "Lenguajes de Marcas")));
        Alumno a10 = new Alumno("35795126J", "Castro", "Hernández", "David", 21, "Masculino", 1010, new ArrayList<>(List.of("FOL", "Programación")));
        Alumno a11 = new Alumno("11111111K", "Ruiz", "Peña", "Marta", 19, "Femenino", 1011, new ArrayList<>(List.of("Programación", "FOL")));
        Alumno a12 = new Alumno("22222222L", "Ortega", "Delgado", "Tomás", 20, "Masculino", 1012, new ArrayList<>(List.of("Bases de Datos", "Entornos de Desarrollo")));
        Alumno a13 = new Alumno("33333333M", "Núñez", "Soto", "Isabel", 21, "Femenino", 1013, new ArrayList<>(List.of("Lenguajes de Marcas", "FOL")));
        Alumno a14 = new Alumno("44444444N", "Vargas", "Reyes", "Joaquín", 22, "Masculino", 1014, new ArrayList<>(List.of("Programación", "Sistemas Informáticos")));
        Alumno a15 = new Alumno("55555555O", "Herrera", "Molina", "Claudia", 18, "Femenino", 1015, new ArrayList<>(List.of("Bases de Datos", "Lenguajes de Marcas")));
        Alumno a16 = new Alumno("66666666P", "Iglesias", "Pardo", "Fernando", 23, "Masculino", 1016, new ArrayList<>(List.of("Entornos de Desarrollo", "FOL")));
        Alumno a17 = new Alumno("77777777Q", "Ramos", "Campos", "Nuria", 20, "Femenino", 1017, new ArrayList<>(List.of("Sistemas Informáticos", "Lenguajes de Marcas")));
        Alumno a18 = new Alumno("88888888R", "Díaz", "Fuentes", "Alberto", 21, "Masculino", 1018, new ArrayList<>(List.of("Programación", "Bases de Datos")));
        Alumno a19 = new Alumno("99999999S", "Cano", "Acosta", "Patricia", 19, "Femenino", 1019, new ArrayList<>(List.of("FOL", "Entornos de Desarrollo")));
        Alumno a20 = new Alumno("10101010T", "León", "Bravo", "Iván", 22, "Masculino", 1020, new ArrayList<>(List.of("Bases de Datos", "Lenguajes de Marcas")));
        Alumno a21 = new Alumno("12121212U", "Medina", "Arias", "Laura", 20, "Femenino", 1021, new ArrayList<>(List.of("Sistemas Informáticos", "FOL")));
        Alumno a22 = new Alumno("13131313V", "Méndez", "Carrasco", "Diego", 18, "Masculino", 1022, new ArrayList<>(List.of("Lenguajes de Marcas", "Programación")));
        Alumno a23 = new Alumno("14141414W", "Pascual", "Andrade", "Sara", 21, "Femenino", 1023, new ArrayList<>(List.of("Entornos de Desarrollo", "Sistemas Informáticos")));
        Alumno a24 = new Alumno("15151515X", "Vega", "Salinas", "Hugo", 19, "Masculino", 1024, new ArrayList<>(List.of("FOL", "Bases de Datos")));
        Alumno a25 = new Alumno("16161616Y", "Navarro", "Cabrera", "Luciana", 22, "Femenino", 1025, new ArrayList<>(List.of("Programación", "Lenguajes de Marcas")));
        Alumno a26 = new Alumno("17171717Z", "Reina", "Lozano", "Mateo", 23, "Masculino", 1026, new ArrayList<>(List.of("Sistemas Informáticos", "Entornos de Desarrollo")));
        Alumno a27 = new Alumno("18181818A", "Giménez", "Benítez", "Eva", 18, "Femenino", 1027, new ArrayList<>(List.of("Bases de Datos", "FOL")));
        Alumno a28 = new Alumno("19191919B", "Domínguez", "Solís", "Pablo", 20, "Masculino", 1028, new ArrayList<>(List.of("Lenguajes de Marcas", "Programación")));
        Alumno a29 = new Alumno("20202020C", "Aguirre", "Rosales", "Valeria", 21, "Femenino", 1029, new ArrayList<>(List.of("Sistemas Informáticos", "FOL")));
        Alumno a30 = new Alumno("21212121D", "Saavedra", "Nieto", "Gabriel", 19, "Masculino", 1030, new ArrayList<>(List.of("Programación", "Bases de Datos")));
        Alumno a31 = new Alumno("22222222E", "Mora", "Del Valle", "Jimena", 18, "Femenino", 1031, new ArrayList<>(List.of("FOL", "Entornos de Desarrollo")));
        Alumno a32 = new Alumno("23232323F", "Soto", "Tejada", "Álvaro", 20, "Masculino", 1032, new ArrayList<>(List.of("Programación", "Sistemas Informáticos")));
        Alumno a33 = new Alumno("24242424G", "Camacho", "Esquivel", "Natalia", 19, "Femenino", 1033, new ArrayList<>(List.of("Bases de Datos", "FOL")));
        Alumno a34 = new Alumno("25252525H", "Palacios", "Barrios", "Rodrigo", 21, "Masculino", 1034, new ArrayList<>(List.of("Lenguajes de Marcas", "Programación")));
        Alumno a35 = new Alumno("26262626I", "Roldán", "Maldonado", "Celia", 22, "Femenino", 1035, new ArrayList<>(List.of("Entornos de Desarrollo", "Lenguajes de Marcas")));
        Alumno a36 = new Alumno("27272727J", "Santana", "Cuéllar", "Héctor", 20, "Masculino", 1036, new ArrayList<>(List.of("Sistemas Informáticos", "Bases de Datos")));
        Alumno a37 = new Alumno("28282828K", "Del Río", "Gallego", "Rebeca", 19, "Femenino", 1037, new ArrayList<>(List.of("FOL", "Programación")));
        Alumno a38 = new Alumno("29292929L", "Peñalosa", "Lara", "Martín", 23, "Masculino", 1038, new ArrayList<>(List.of("Bases de Datos", "Entornos de Desarrollo")));
        Alumno a39 = new Alumno("30303030M", "Castaño", "Marín", "Daniela", 18, "Femenino", 1039, new ArrayList<>(List.of("Sistemas Informáticos", "FOL")));
        Alumno a40 = new Alumno("31313131N", "Salas", "Peralta", "Álex", 22, "Masculino", 1040, new ArrayList<>(List.of("Programación", "Lenguajes de Marcas")));
        Alumno a41 = new Alumno("32323232O", "Alonso", "Serna", "Noelia", 20, "Femenino", 1041, new ArrayList<>(List.of("Entornos de Desarrollo", "Sistemas Informáticos")));
        Alumno a42 = new Alumno("33333333P", "Calderón", "Rivas", "Óscar", 21, "Masculino", 1042, new ArrayList<>(List.of("Lenguajes de Marcas", "FOL")));
        Alumno a43 = new Alumno("34343434Q", "Beltrán", "Segura", "Irene", 19, "Femenino", 1043, new ArrayList<>(List.of("Bases de Datos", "Entornos de Desarrollo")));
        Alumno a44 = new Alumno("35353535R", "Cordero", "Miranda", "Adrián", 20, "Masculino", 1044, new ArrayList<>(List.of("Sistemas Informáticos", "FOL")));
        Alumno a45 = new Alumno("36363636S", "Gallardo", "Requena", "Alicia", 22, "Femenino", 1045, new ArrayList<>(List.of("Programación", "Bases de Datos")));
        Alumno a46 = new Alumno("37373737T", "Zamora", "Suárez", "Marco", 23, "Masculino", 1046, new ArrayList<>(List.of("Lenguajes de Marcas", "Entornos de Desarrollo")));
        Alumno a47 = new Alumno("38383838U", "Ibáñez", "Valverde", "Sofía", 18, "Femenino", 1047, new ArrayList<>(List.of("FOL", "Programación")));
        Alumno a48 = new Alumno("39393939V", "Rosales", "Esteban", "Bruno", 21, "Masculino", 1048, new ArrayList<>(List.of("Sistemas Informáticos", "Bases de Datos")));
        Alumno a49 = new Alumno("40404040W", "Mejía", "Cervantes", "Clara", 20, "Femenino", 1049, new ArrayList<>(List.of("Lenguajes de Marcas", "FOL")));
        Alumno a50 = new Alumno("41414141X", "Barrios", "Montes", "Iván", 19, "Masculino", 1050, new ArrayList<>(List.of("Programación", "Entornos de Desarrollo")));
        em.persist(a1);
        em.persist(a2);
        em.persist(a3);
        em.persist(a4);
        em.persist(a5);
        em.persist(a6);
        em.persist(a7);
        em.persist(a8);
        em.persist(a9);
        em.persist(a10);
        em.persist(a11);
        em.persist(a12);
        em.persist(a13);
        em.persist(a14);
        em.persist(a15);
        em.persist(a16);
        em.persist(a17);
        em.persist(a18);
        em.persist(a19);
        em.persist(a20);
        em.persist(a21);
        em.persist(a22);
        em.persist(a23);
        em.persist(a24);
        em.persist(a25);
        em.persist(a26);
        em.persist(a27);
        em.persist(a28);
        em.persist(a29);
        em.persist(a30);
        em.persist(a31);
        em.persist(a32);
        em.persist(a33);
        em.persist(a34);
        em.persist(a35);
        em.persist(a36);
        em.persist(a37);
        em.persist(a38);
        em.persist(a39);
        em.persist(a40);
        em.persist(a41);
        em.persist(a42);
        em.persist(a43);
        em.persist(a44);
        em.persist(a45);
        em.persist(a46);
        em.persist(a47);
        em.persist(a48);
        em.persist(a49);
        em.persist(a50);

        Profesor p1 = new Profesor("50000001A", "Martínez", "Rojas", "Lucía", 45, "Femenino", 2000, new ArrayList<>(List.of("Programación", "Bases de Datos")));
        Profesor p2 = new Profesor("50000002B", "Gómez", "Hernández", "Carlos", 50, "Masculino", 2001, new ArrayList<>(List.of("Sistemas Informáticos", "FOL")));
        Profesor p3 = new Profesor("50000003C", "López", "Fernández", "Isabel", 38, "Femenino", 2002, new ArrayList<>(List.of("Lenguajes de Marcas", "Entornos de Desarrollo")));
        Profesor p4 = new Profesor("50000004D", "Ruiz", "Morales", "Álvaro", 42, "Masculino", 2003, new ArrayList<>(List.of("Programación", "Lenguajes de Marcas")));
        Profesor p5 = new Profesor("50000005E", "Díaz", "Cruz", "María", 47, "Femenino", 2004, new ArrayList<>(List.of("FOL", "Bases de Datos")));
        Profesor p6 = new Profesor("50000006F", "Serrano", "Ortega", "Javier", 40, "Masculino", 2005, new ArrayList<>(List.of("Entornos de Desarrollo", "Sistemas Informáticos")));
        Profesor p7 = new Profesor("50000007G", "Castillo", "Navarro", "Elena", 36, "Femenino", 2006, new ArrayList<>(List.of("Bases de Datos", "Lenguajes de Marcas")));
        Profesor p8 = new Profesor("50000008H", "Vega", "Delgado", "Tomás", 39, "Masculino", 2007, new ArrayList<>(List.of("Programación", "Entornos de Desarrollo")));
        Profesor p9 = new Profesor("50000009I", "Paredes", "Romero", "Sandra", 44, "Femenino", 2008, new ArrayList<>(List.of("FOL", "Sistemas Informáticos")));
        Profesor p10 = new Profesor("50000010J", "Cano", "Leiva", "Andrés", 41, "Masculino", 2009, new ArrayList<>(List.of("Lenguajes de Marcas", "Programación")));
        em.persist(p1);
        em.persist(p2);
        em.persist(p3);
        em.persist(p4);
        em.persist(p5);
        em.persist(p6);
        em.persist(p7);
        em.persist(p8);
        em.persist(p9);
        em.persist(p10);
        em.getTransaction().commit();
        em.close();

    }
}