package dev.alejandrosahonero.db;

import javax.persistence.EntityManager;
import java.util.ArrayList;

public class ExampleDB {
    public static void create(){
        EntityManager em = Conector.getEntityManager();

        em.getTransaction().begin();

        ArrayList<Asignatura> asigDAM_DAW1 = new ArrayList<>();
        Asignatura programacion = new Asignatura("PRO", "Programación","Aprenderás a crear programas usando lenguajes como Java, resolviendo problemas con lógica y estructuras básicas");
        em.persist(programacion);
        asigDAM_DAW1.add(programacion);
        Asignatura sistemas = new Asignatura("SIS", "Sistemas Informáticos", "Aprenderás a instalar, configurar y mantener sistemas operativos y redes locales.");
        em.persist(sistemas);
        asigDAM_DAW1.add(sistemas);
        Asignatura bbdd = new Asignatura("BBDD", "Bases de Datos", "Verás cómo organizar, almacenar y gestionar datos con sistemas como MySQL o MariaDB.");
        em.persist(bbdd);
        asigDAM_DAW1.add(bbdd);
        Asignatura lenguajeMarcas = new Asignatura("LM", "Lenguajes de Marcas", "Conocerás lenguajes como HTML y XML para estructurar y presentar información en la web.");
        em.persist(lenguajeMarcas);
        asigDAM_DAW1.add(lenguajeMarcas);
        Asignatura entornos = new Asignatura("ENT", "Entornos de Desarrollo", "Estudiarás herramientas y metodologías usadas en el desarrollo de software.");
        em.persist(entornos);
        asigDAM_DAW1.add(entornos);
        Asignatura fol = new Asignatura("FOL", "Formación y Orientación Laboral", "Te preparan para el mundo laboral, derechos del trabajador y prevención de riesgos.");
        em.persist(fol);
        asigDAM_DAW1.add(fol);
        Asignatura digi = new Asignatura("DIG", "Empresa e Iniciativa Emprendedora", "Aprenderás lo básico sobre cómo funciona una empresa y cómo emprender un negocio.");
        em.persist(digi);
        asigDAM_DAW1.add(digi);

        Modulo DAM1 = new Modulo("DAM1", "Desarrollo de aplicaciones multiplataforma", "Te prepararás para crear apps en ordenadores, móviles y otros dispositivos, usando distintos lenguajes y tecnologías", asigDAM_DAW1);
        em.persist(DAM1);
        Modulo DAW1 = new Modulo("DAW1", "Desarrollo de aplicaciones web", "Te enfocarás en crear y mantener sitios y aplicaciones web, tanto del lado del cliente como del servidor", asigDAM_DAW1);
        em.persist(DAW1);

        ArrayList<Asignatura> asigDAM2 = new ArrayList<>();
        Asignatura interfaces = new Asignatura("DI", "Desarrollo de Interfaces", "Aprenderás a crear interfaces gráficas de usuario funcionales y atractivas, usando tecnologías como JavaFX o Swing.");
        em.persist(interfaces);
        asigDAM2.add(interfaces);
        Asignatura accesoDatos = new Asignatura("AD", "Acceso a Datos", "Estudiarás cómo conectar aplicaciones con bases de datos, manejar información y realizar operaciones CRUD.");
        em.persist(accesoDatos);
        asigDAM2.add(accesoDatos);
        Asignatura procesos = new Asignatura("PSP", "Programación de Servicios y Procesos", "Verás cómo gestionar hilos, procesos y comunicaciones en red para crear aplicaciones más complejas.");
        em.persist(procesos);
        asigDAM2.add(procesos);
        Asignatura gestionEmpresa = new Asignatura("SGE", "Sistemas de Gestión Empresarial", "Conocerás herramientas como ERP o CRM que utilizan las empresas para gestionar su actividad.");
        em.persist(gestionEmpresa);
        asigDAM2.add(gestionEmpresa);
        Asignatura moviles = new Asignatura("DAM", "Desarrollo de Aplicaciones Multiplataforma", "Desarrollarás aplicaciones para diferentes dispositivos y sistemas usando frameworks multiplataforma.");
        em.persist(moviles);
        asigDAM2.add(moviles);
        Asignatura iniciativa = new Asignatura("EIE", "Empresa e Iniciativa Emprendedora", "Aprenderás a como poner en marcha tu propia empresa");
        em.persist(iniciativa);
        asigDAM2.add(iniciativa);
        Asignatura proyectoDam = new Asignatura("PROY", "Proyecto de Desarrollo de Aplicaciones Multiplataforma", "Aplicarás todo lo aprendido para crear un proyecto completo y funcional, trabajando en equipo o individualmente.");
        em.persist(proyectoDam);
        asigDAM2.add(proyectoDam);
        Asignatura fctDam = new Asignatura("FCT", "Formación en Centros de Trabajo", "Realizarás prácticas en una empresa para aplicar tus conocimientos en un entorno profesional real");
        em.persist(fctDam);
        asigDAM2.add(fctDam);

        Modulo DAM2 = new Modulo("DAM1", "Desarrollo de aplicaciones multiplataforma", "Te prepararás para crear apps en ordenadores, móviles y otros dispositivos, usando distintos lenguajes y tecnologías", asigDAM2);
        em.persist(DAM2);

        ArrayList<Asignatura> asigDAW2 = new ArrayList<>();
        Asignatura entorno = new Asignatura("DWEC", "Desarrollo Web en Entorno Cliente", "Aprenderás a crear páginas dinámicas con HTML, CSS y JavaScript para el lado del cliente");
        em.persist(entorno);
        asigDAW2.add(entorno);
        Asignatura servidor = new Asignatura("DWES", "Desarrollo Web en Entorno Servidor", "Desarrollarás aplicaciones web dinámicas usando tecnologías como PHP o Java en el servidor");
        em.persist(servidor);
        asigDAW2.add(servidor);
        Asignatura despliegue = new Asignatura("DAW", "Despliegue de Aplicaciones Web", "Estudiarás cómo publicar, mantener y administrar aplicaciones web en servidores");
        em.persist(despliegue);
        asigDAW2.add(despliegue);
        Asignatura diseno = new Asignatura("DIW", "Diseño de Interfaces Web", "Aprenderás a crear interfaces atractivas y usables, aplicando diseño visual y experiencia de usuario");
        em.persist(diseno);
        asigDAW2.add(diseno);
        Asignatura empresa = new Asignatura("EIE", "Empresa e Iniciativa Emprendedora", "Aprenderás lo básico sobre cómo funciona una empresa y cómo emprender un negocio");
        em.persist(empresa);
        asigDAW2.add(empresa);
        Asignatura proyectoDaw = new Asignatura("PROY", "Proyecto de Desarrollo de Aplicaciones Web", "Aplicarás todo lo aprendido para desarrollar una aplicación web completa");
        em.persist(proyectoDaw);
        asigDAW2.add(proyectoDaw);
        Asignatura fctDaw = new Asignatura("FCT", "Formación en Centros de Trabajo", "Realizarás prácticas en una empresa para aplicar tus conocimientos en un entorno profesional real");
        em.persist(entorno);
        asigDAW2.add(entorno);

        Modulo DAW2 = new Modulo("DAW1", "Desarrollo de aplicaciones web", "Te enfocarás en crear y mantener sitios y aplicaciones web, tanto del lado del cliente como del servidor", asigDAW2);
        em.persist(DAW2);

        Alumno a1 = new Alumno("12345678A", "García", "López", "Ana", (short)19, "Femenino", DAM1, "1001", asigDAM_DAW1);
        em.persist(a1);
        Alumno a2 = new Alumno("12345679B", "Martínez", "Pérez", "Luis", (short)20, "Masculino", DAW2, "1002", asigDAW2);
        em.persist(a2);
        Alumno a3 = new Alumno("12345680C", "Rodríguez", "Sánchez", "María", (short)18, "Femenino", DAW1, "1003", asigDAM_DAW1);
        em.persist(a3);
        Alumno a4 = new Alumno("12345681D", "López", "Fernández", "Carlos", (short)21, "Masculino", DAM2, "1004", asigDAM2);
        em.persist(a4);
        Alumno a5 = new Alumno("12345682E", "Gómez", "Martín", "Lucía", (short)22, "Femenino", DAW1, "1005", asigDAM_DAW1);
        em.persist(a5);
        Alumno a6 = new Alumno("12345683F", "Hernández", "Ruiz", "Javier", (short)23, "Masculino", DAW2, "1006", asigDAW2);
        em.persist(a6);
        Alumno a7 = new Alumno("12345684G", "Jiménez", "Moreno", "Carmen", (short)19, "Femenino", DAW2, "1007", asigDAW2);
        em.persist(a7);
        Alumno a8 = new Alumno("12345685H", "Díaz", "Álvarez", "Pedro", (short)20, "Masculino", DAM1, "1008", asigDAM_DAW1);
        em.persist(a8);
        Alumno a9 = new Alumno("12345686I", "Morales", "Romero", "Sara", (short)21, "Femenino", DAW1, "1009", asigDAM_DAW1);
        em.persist(a9);
        Alumno a10 = new Alumno("12345687J", "Ortega", "Navarro", "Miguel", (short)22, "Masculino", DAW2, "1010", asigDAW2);
        em.persist(a10);
        Alumno a11 = new Alumno("12345688K", "Rubio", "Molina", "Elena", (short)23, "Femenino", DAW1, "1011", asigDAM_DAW1);
        em.persist(a11);
        Alumno a12 = new Alumno("12345689L", "Serrano", "Delgado", "Antonio", (short)18, "Masculino", DAW2, "1012", asigDAW2);
        em.persist(a12);
        Alumno a13 = new Alumno("12345690M", "Ramírez", "Castro", "Isabel", (short)19, "Femenino", DAM1, "1013", asigDAM_DAW1);
        em.persist(a13);
        Alumno a14 = new Alumno("12345691N", "Flores", "Ortiz", "David", (short)20, "Masculino", DAM2, "1014", asigDAM2);
        em.persist(a14);
        Alumno a15 = new Alumno("12345692O", "Suárez", "Rubio", "Marta", (short)21, "Femenino", DAM1, "1015", asigDAM_DAW1);
        em.persist(a15);
        Alumno a16 = new Alumno("12345693P", "Castillo", "Marín", "Fernando", (short)22, "Masculino", DAW2, "1016", asigDAW2);
        em.persist(a16);
        Alumno a17 = new Alumno("12345694Q", "Cruz", "Iglesias", "Patricia", (short)23, "Femenino", DAM2, "1017", asigDAM2);
        em.persist(a17);
        Alumno a18 = new Alumno("12345695R", "Silva", "Vega", "Hugo", (short)18, "Masculino", DAM1, "1018", asigDAM_DAW1);
        em.persist(a18);
        Alumno a19 = new Alumno("12345696S", "Vargas", "Lorenzo", "Natalia", (short)19, "Femenino", DAW2, "1019", asigDAW2);
        em.persist(a19);
        Alumno a20 = new Alumno("12345697T", "Reyes", "Santos", "Andrés", (short)20, "Masculino", DAW1, "1020", asigDAM_DAW1);
        em.persist(a20);
        Alumno a21 = new Alumno("12345698U", "Peña", "Calvo", "Sofía", (short)21, "Femenino", DAM1, "1021", asigDAM_DAW1);
        em.persist(a21);
        Alumno a22 = new Alumno("12345699V", "Aguilar", "Nieto", "Iván", (short)22, "Masculino", DAW2, "1022", asigDAW2);
        em.persist(a22);
        Alumno a23 = new Alumno("12345700W", "Del Río", "Jimeno", "Laura", (short)23, "Femenino", DAM1, "1023", asigDAM_DAW1);
        em.persist(a23);
        Alumno a24 = new Alumno("12345701X", "Fuentes", "Blasco", "Sergio", (short)18, "Masculino", DAM2, "1024", asigDAM2);
        em.persist(a24);
        Alumno a25 = new Alumno("12345702Y", "Gallardo", "Mateo", "Alba", (short)19, "Femenino", DAW1, "1025", asigDAM_DAW1);
        em.persist(a25);
        Alumno a26 = new Alumno("12345703Z", "Ibañez", "Pardo", "Adrián", (short)20, "Masculino", DAW1, "1026", asigDAM_DAW1);
        em.persist(a26);
        Alumno a27 = new Alumno("12345704A", "Lara", "Carrasco", "Julia", (short)21, "Femenino", DAM1, "1027", asigDAM_DAW1);
        em.persist(a27);
        Alumno a28 = new Alumno("12345705B", "Méndez", "Valle", "Raúl", (short)22, "Masculino", DAW2, "1028", asigDAW2);
        em.persist(a28);
        Alumno a29 = new Alumno("12345706C", "Navas", "Franco", "Cristina", (short)23, "Femenino", DAW2, "1029", asigDAW2);
        em.persist(a29);
        Alumno a30 = new Alumno("12345707D", "Ojeda", "Rey", "Álvaro", (short)18, "Masculino", DAM1, "1030", asigDAM_DAW1);
        em.persist(a30);
        Alumno a31 = new Alumno("12345708E", "Palacios", "Soto", "Mónica", (short)19, "Femenino", DAW2, "1031", asigDAW2);
        em.persist(a31);
        Alumno a32 = new Alumno("12345709F", "Quintana", "Ríos", "Mario", (short)20, "Masculino", DAW1, "1032", asigDAM_DAW1);
        em.persist(a32);
        Alumno a33 = new Alumno("12345710G", "Ramos", "Solís", "Nuria", (short)21, "Femenino", DAM1, "1033", asigDAM_DAW1);
        em.persist(a33);
        Alumno a34 = new Alumno("12345711H", "Salazar", "Toledo", "Pablo", (short)22, "Masculino", DAM2, "1034", asigDAM2);
        em.persist(a34);
        Alumno a35 = new Alumno("12345712I", "Tejada", "Velasco", "Beatriz", (short)23, "Femenino", DAM2, "1035", asigDAM2);
        em.persist(a35);
        Alumno a36 = new Alumno("12345713J", "Urbano", "Zamora", "Diego", (short)18, "Masculino", DAM2, "1036", asigDAM2);
        em.persist(a36);
        Alumno a37 = new Alumno("12345714K", "Varela", "Campos", "Alicia", (short)19, "Femenino", DAW1, "1037", asigDAM_DAW1);
        em.persist(a37);
        Alumno a38 = new Alumno("12345715L", "Yáñez", "Del Valle", "Óscar", (short)20, "Masculino", DAM1, "1038", asigDAM_DAW1);
        em.persist(a38);
        Alumno a39 = new Alumno("12345716M", "Zaragoza", "Gallego", "Irene", (short)21, "Femenino", DAM1, "1039", asigDAM_DAW1);
        em.persist(a39);
        Alumno a40 = new Alumno("12345717N", "Acevedo", "Hidalgo", "Alejandro", (short)22, "Masculino", DAM2, "1040", asigDAM2);
        em.persist(a40);
        Alumno a41 = new Alumno("12345718O", "Barrios", "Izquierdo", "Daniela", (short)23, "Femenino", DAW1, "1041", asigDAM_DAW1);
        em.persist(a41);
        Alumno a42 = new Alumno("12345719P", "Cano", "Jurado", "Tomás", (short)18, "Masculino", DAM1, "1042", asigDAM_DAW1);
        em.persist(a42);
        Alumno a43 = new Alumno("12345720Q", "Delgado", "Llamas", "Noelia", (short)19, "Femenino", DAW2, "1043", asigDAW2);
        em.persist(a43);
        Alumno a44 = new Alumno("12345721R", "Escobar", "Miralles", "Ernesto", (short)20, "Masculino", DAW2, "1044", asigDAW2);
        em.persist(a44);
        Alumno a45 = new Alumno("12345722S", "Franco", "Nieto", "Andrea", (short)21, "Femenino", DAW1, "1045", asigDAM_DAW1);
        em.persist(a45);
        Alumno a46 = new Alumno("12345723T", "Giménez", "Ochoa", "Luis", (short)22, "Masculino", DAW1, "1046", asigDAM_DAW1);
        em.persist(a46);
        Alumno a47 = new Alumno("12345724U", "Herrera", "Paz", "Valeria", (short)23, "Femenino", DAM1, "1047", asigDAM_DAW1);
        em.persist(a47);
        Alumno a48 = new Alumno("12345725V", "Iglesias", "Quirós", "Rubén", (short)18, "Masculino", DAW2, "1048", asigDAW2);
        em.persist(a48);
        Alumno a49 = new Alumno("12345726W", "Jurado", "Rodrigo", "Paula", (short)19, "Femenino", DAW2, "1049", asigDAW2);
        em.persist(a49);
        Alumno a50 = new Alumno("12345727X", "López", "Sáez", "Gonzalo", (short)20, "Masculino", DAW2, "1050", asigDAW2);
        em.persist(a50);

        ArrayList<Modulo> modExample = new ArrayList<>();
        modExample.add(DAM1);
        Profesor p1 = new Profesor("50000001A", "Martínez", "Rojas", "Lucía", (short)45, "Femenino", "2000", modExample);
        em.persist(p1);
        Profesor p2 = new Profesor("50000002B", "Gómez", "López", "Carlos", (short)50, "Masculino", "2001", modExample);
        em.persist(p2);
        Profesor p3 = new Profesor("50000003C", "Sánchez", "Díaz", "María", (short)42, "Femenino", "2002", modExample);
        em.persist(p3);
        Profesor p4 = new Profesor("50000004D", "Ramírez", "Pérez", "Andrés", (short)47, "Masculino", "2003", modExample);
        em.persist(p4);
        Profesor p5 = new Profesor("50000005E", "Fernández", "Ruiz", "Carmen", (short)44, "Femenino", "2004", modExample);
        em.persist(p5);
        Profesor p6 = new Profesor("50000006F", "Castillo", "Moreno", "José", (short)49, "Masculino", "2005", modExample);
        em.persist(p6);
        Profesor p7 = new Profesor("50000007G", "Iglesias", "Ortiz", "Elena", (short)41, "Femenino", "2006", modExample);
        em.persist(p7);
        Profesor p8 = new Profesor("50000008H", "Navarro", "Molina", "Luis", (short)53, "Masculino", "2007", modExample);
        em.persist(p8);
        Profesor p9 = new Profesor("50000009I", "Delgado", "Vega", "Beatriz", (short)46, "Femenino", "2008", modExample);
        em.persist(p9);
        Profesor p10 = new Profesor("50000010J", "Cruz", "Serrano", "Manuel", (short)48, "Masculino", "2009", modExample);
        em.persist(p10);

        em.getTransaction().commit();
        em.close();
    }
}
